### PR TITLE
Platform Engineer test implementation

### PR DESCRIPTION
**Pull request by TyrasNistru**
## About You

Name: Dniester Amorim de Aguiar

Email: dniester.amorim@gmail.com

Whatsapp: +55 81 981494221

Linkedin: https://www.linkedin.com/in/dniester-amorim-de-aguiar-38998955/

## About your solution
The validation of the image size could be better (using a HEAD request instead of GET). The error handling is a bit crude as well, could go cover more edge cases as well, but for simplicity, they were omitted.

## Your findings
Firstm I tried making a HEAD request to grab the content-lenght without initiating a download of the images, but it did not work: For some reason, the request callback never got called, and ended up failing by timeout. Changing the request type (and only that) to a GET made it work, for unknown reasons. The servers used to test supported HEAD requests, as I tried with cURL and browsers and it worked. In the end, decided not to waste too much time on it.

## How to run your code?
The platform-engineer-2 is a project folder. Opening it on VS Code should work out-of-the-box. the package.json define both a start:dev script (using npx ts-node) and test script (using jest).

Running it with the start:dev script will run the function using the sample json file provided, and downloading the images to static/images subfolder.

### CODE REVIEW

**Comment by cinguilherme** [comment]
@TyrasNistru did you do the piece where the images destination should be grouped in subfolders by domain? If so, can you point out where that is?

**Comment by cinguilherme** [comment]
@TyrasNistru to be fair, I noticed my description was incomplete on the problem statement, this is my fault.
I'm fixing the text to be more explicit about this. But for each different domain where the imagens are coming from, we need a appropriately named folder and the downloads from that domain need to be placed in that folder.

**Comment by TyrasNistru** [comment]
Yes, I did. In the saveToFile function, when I build save path, you can notice that I append the hostname to the path.

**Comment by cinguilherme** [comment]
approved.

**Pull request closed without merging**
